[build]
builder = "NIXPACKS"
buildCommand = "NITRO_PRESET=node-server npm run build"

[deploy]
startCommand = "HOST=0.0.0.0 NITRO_HOST=0.0.0.0 node .output/server/index.mjs"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"

